---
- name: First play
  hosts: all
  become: true
  become_method: sudo
  tasks:
    - name: Update apt-get repo and cache
      apt:
        update_cache=yes
        force_apt_get=yes
        cache_valid_time=3600
    - name: Packages installation
      apt:
        name:
          - sysstat
          - mariadb-server
          - net-tools
        state: latest
    - name: Upgrade all apt packages
      apt:
        upgrade: dist
        force_apt_get: yes
    - name: Reboot
      reboot:
        msg: "Reboot initiated by Ansible"
        connect_timeout: 5
        reboot_timeout: 200
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: uptime

